public class Me {
// <- keyword
//     ^ keyword
//           ^ class.declaration
//              ^ punctuation
   public enum Season {WINTER, SPRING, SUMMER, FALL}
// ^ keyword
//        ^ keyword
//             ^ enum.declaration
//                    ^ punctuation
//                     ^ enumMember.declaration
//                           ^ punctuation
//                             ^ enumMember.declaration
//                                   ^ punctuation
//                                     ^ enumMember.declaration
//                                           ^ punctuation
//                                             ^ enumMember.declaration
//                                                 ^ punctuation
  {
//^ punctuation
    Season s = Season.SPRING;
//  ^ type
//         ^ variable.declaration
//           ^ operator
//             ^ enum.declaration
//                   ^ punctuation
//                    ^ enumMember.declaration
//                          ^ punctuation


  }
//^ punctuation
}
// <- punctuation