global class Me implements Interface1, Interface2 {}
// <- keyword
//     ^ keyword
//           ^ class.declaration
//              ^ keyword
//                         ^ interface
//                                   ^ punctuation
//                                     ^ interface
//                                                ^ punctuation
//                                                 ^ punctuation